booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'
urlpatterns = [
    path('', views.BookingView.as_view(), name='index'),
    path('<str:booking_code>/confirmation/', views.confirmation, name='confirmation'),
    path('<str:ticket_code>/pdf/', views.pdf_view, name='pdf'),
    path('<str:ticket_code>/verify', views.VerificationView.as_view(), name='verify'),
    path('<str:booking_code>/resend_mail/', views.ResendConfirmationMail.as_view(), name='resend')
]

ticket_system/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.views.generic.base import RedirectView
from django.conf import settings

# Redirect anything to renovation app if renovation mode is active
if settings.RUN_IN_RENOVATION_MODE:
    urlpatterns = [
        re_path(r'^(?P<url>.*)$', include('closed_for_renovation.urls'))
    ]
else:
    urlpatterns = [
        path('', RedirectView.as_view(url='/booking')),
        path('booking/', include('booking.urls')),
        path('closed/', include('closed_for_renovation.urls')),
        path('admin/', admin.site.urls),
    ]

booking/models.py
from django.db import models
from django.db.models import Sum
from django.core.validators import MinValueValidator, MaxValueValidator, BaseValidator
from django.utils import formats


class Base(models.Model):

    class Meta:
        abstract = True


class Performance(Base):
    title = models.CharField(max_length=200, help_text="Performance title")
    start = models.DateTimeField(help_text="Date and time of performance")
    capacity = models.IntegerField(default=0, help_text='Maximum number of tickes')

    def __str__(self):
        return self.title

    @classmethod
    def get_with_tickets_available(cls, pk=None):
        if pk is None:
            performances = cls.objects.all().annotate(
                tickets_booked=Sum('booking__number_of_tickets')
            )
        else:
            performances = cls.objects.get(pk=pk).annotate(
                tickets_booked=Sum('booking__number_of_tickets')
            )
        return performances

    def tickets_available(self):
        tickets_booked = Performance.objects.filter(id=self.id).annotate(
            tickets_booked=Sum('booking__number_of_tickets')
        )[0].tickets_booked

        return self.capacity - int(tickets_booked or 0)

    @property
    def start_date(self):
        return formats.date_format(self.start, format='DATE_FORMAT', use_l10n=True)

    @property
    def start_time(self):
        return formats.date_format(self.start, format='TIME_FORMAT', use_l10n=True)


class Booking(Base):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    booking_date = models.DateTimeField(auto_now_add=True)
    performance = models.ForeignKey(Performance, on_delete=models.CASCADE)
    number_of_tickets = models.IntegerField(
        blank=True,
        default=0,
        validators=[
            MinValueValidator(1, 'Mindestens ein Ticket'),
            MaxValueValidator(8, 'Maximal 8 Tickets pro Buchung erlaubt')
        ]
    )
    code = models.CharField(max_length=10, unique=True, blank=True)

    def __str__(self):
        return self.email


class Ticket(Base):
    code = models.CharField(max_length=10, unique=True)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    check_in_flag = models.BooleanField(default=False)

booking/forms.py
from django.forms import ModelForm, ChoiceField, CharField, TextInput
from django.core.exceptions import ObjectDoesNotExist
from .models import Booking, Performance


def get_performance_choices():
    performances = Performance.get_with_tickets_available()
    performance_choices = []
    for performance in performances:
        title = "{} (Noch {} tickets verfügbar)".format(
            performance.title,
            str(performance.tickets_available())
        )
        performance_choices.append((performance.id, title))
    return performance_choices


class BookingForm(ModelForm):
    performance = ChoiceField(choices=get_performance_choices(), label='Vorstellung')
    email_confirmation = CharField(max_length=254, required=True, label='E-Mail (zur Bestätigung)',
                                   widget=TextInput(attrs={'placeholder': 'Geben Sie Ihre E-Mail-Adresse erneut ein.'}))
    performance_model = None

    class Meta:
        model = Booking
        fields = ['first_name', 'last_name', 'number_of_tickets', 'email', 'email_confirmation']
        labels = {
            'first_name': 'Vorname',
            'last_name': 'Nachname',
            'number_of_tickets': 'Anzahl:',
            'email': 'E-Mail-Adresse'
        }
        help_texts = {
            'first_name': 'Informationen über den Schutz Ihrer Daten, finden Sie in der Datenschutzerklärung.',
            'last_name': '',
            'number_of_tickets': '',
            'email': ''
        }
        widgets = {
            'first_name': TextInput(attrs={'placeholder': 'Vorname'}),
            'last_name': TextInput(attrs={'placeholder': 'Nachname'}),
            'email': TextInput(attrs={'placeholder': 'Geben Sie Ihre E-Mail-Adresse ein.'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['performance'].choices = get_performance_choices()

    def is_valid(self):
        valid = super(BookingForm, self).is_valid()
        if not valid:
            return valid

        # Check mail confirmation
        if self.cleaned_data['email'] != self.cleaned_data['email_confirmation']:
            self.add_error('email', 'Bitte überprüfen Sie die E-Mail-Adresse')
            return False

        # Check valid performance
        try:
            self.performance_model = Performance.objects.get(pk=self.cleaned_data['performance'])
        except ObjectDoesNotExist:
            self.add_error('performance', "Ungültige Vorstellung!")
            return False

        # Check if enough tickets are available
        tickets_available = self.performance_model.tickets_available()
        booked_tickets = self.cleaned_data['number_of_tickets']
        if tickets_available < booked_tickets:
            self.add_error('performance', 'Vorstellung ist leider schon ausverkauft!')
            return False

        return valid

booking/views.py
import string
import random
from django.shortcuts import render
from django.template.loader import render_to_string
from django.http import HttpResponseRedirect, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.views import generic, View
from django.urls import reverse
from django.core.mail import EmailMultiAlternatives
from django.utils.html import strip_tags
from django.apps import apps
import qrcode as qr
from .forms import BookingForm
from .models import Performance, Booking, Ticket

from reportlab.pdfgen.canvas import Canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib.units import mm
from io import BytesIO


def confirmation(request, booking_code):
    try:
        booking = Booking.objects.get(code=booking_code)
        tickets = booking.ticket_set.all()
    except ObjectDoesNotExist:
        return render(request, 'booking/invalid_ticket_code.html')

    return render(
        request,
        'booking/confirmation.html',
        context={
            'booking': booking,
            'tickets': tickets
        }
    )


def create_code():
    return ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(10))


def send_confirmation_mail(request, booking):
    # Send confirmation mail
    subject = 'Ihre Bestellung'

    html_content = render_to_string('booking/mail.html', context={
        'request': request,
        'booking': booking,
        'tickets': booking.ticket_set.all()
    })
    text_content = strip_tags(html_content)

    message = EmailMultiAlternatives(
        subject='Ihre Bestellung',
        body=text_content,
        to=[booking.email],
        headers={
            'Message-ID': 'foo'
        }
    )
    message.attach_alternative(html_content, 'text/html')

    # @todo Implement proper error handling
    try:
        message.send()
    except Exception:
        pass


class BookingView(View):
    form_class = BookingForm
    template_name = "booking/base.html"

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        number_of_tickets_available_per_performance = []
        number_of_tickets_booked_total = 0
        number_of_tickets_available_total = 0

        performances = Performance.objects.all()
        for performance in performances:
            number_of_tickets_available_per_performance.append(performance.tickets_available())
            number_of_tickets_booked_total += performance.capacity - performance.tickets_available()
            number_of_tickets_available_total += performance.tickets_available()

        return render(
            request,
            self.template_name,
            context={
                'number_of_tickets_available_per_performance': number_of_tickets_available_per_performance,
                'number_of_tickets_booked_total': number_of_tickets_booked_total,
                'number_of_tickets_available_total': number_of_tickets_available_total,
                'performances': performances,
                'form': form
            }
        )

    def post(self, request, *args, **kwargs):
        form = BookingForm(request.POST)
        if form.is_valid():
            # Prepare new booking
            booking = Booking(
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                number_of_tickets=form.cleaned_data['number_of_tickets'],
                performance=form.performance_model,
                code=create_code()
            )
            booking.save()

            # Create the tickets
            tickets = []
            for i in range(booking.number_of_tickets):
                ticket = Ticket(
                    booking=booking,
                    code=create_code()
                )
                ticket.save()
                tickets.append(ticket)

            send_confirmation_mail(request, booking)

            return HttpResponseRedirect(reverse('booking:confirmation', args=(booking.code,)))
        else:
            return render(request, self.template_name, context={'form': form})


def pdf_view(request, ticket_code):
    try:
        ticket = Ticket.objects.get(code=ticket_code)
        booking = ticket.booking
    except ObjectDoesNotExist:
        return render(request, 'booking/invalid_ticket_code.html')

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="ticket.pdf"'

    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    pdfmetrics.registerFont(TTFont('ComicBd', 'booking/templates/booking/comicbd.ttf'))

    p = Canvas(response, pagesize=(260*mm, 150*mm), pageCompression=1)

    image_path = 'booking/templates/booking/ticket.png'

    image = ImageReader(image_path)
    p.drawImage(image, 0, 0, 260*mm, 150*mm, mask='auto')

    p.setFont('ComicBd', 20)

    p.drawString(70*mm, 90*mm, '{},'.format(booking.last_name))
    p.drawString(70*mm, 80*mm, booking.first_name)

    p.drawString(165*mm, 90*mm, '{}'.format(booking.performance.title))
    p.drawString(165*mm, 80*mm, booking.performance.start_date)
    p.drawString(165*mm, 70*mm, booking.performance.start_time)

    p.setFont('Times-Bold', 24)
    p.drawString(192*mm, 18*mm, ticket.code)

    if apps.get_app_config('booking').use_qr_codes:

        # Create QRcode
        qr_code = qr.QRCode(
            version=1,
            error_correction=qr.ERROR_CORRECT_L,
            box_size=3,
            border=4
        )

        verification_url = 'http://{}{}'.format(
            request.get_host(),
            reverse('booking:verify', args=(ticket_code,))
        )
        qr_code.add_data(verification_url)
        img = qr_code.make_image(fill_color="black", back_color="white")
        raw_img = BytesIO()
        img.save(raw_img, format='PNG')
        p.drawImage(ImageReader(raw_img), 210*mm, 35*mm, mask='auto')

    p.showPage()
    p.save()

    return response


class VerificationView(View):
    template_name = 'booking/verify.html'

    def get(self, request, ticket_code=None):
        if ticket_code is None:
            return render(request, self.template_name, context={'ticket': None, 'checkin_ok': False})
        try:
            ticket = Ticket.objects.get(code=ticket_code)
        except ObjectDoesNotExist:
            return render(request, self.template_name, context={'ticket': None, 'checkin_ok': False})

        ticket.check_in_flag = True
        ticket.save()

        return render(request, self.template_name, context={'ticket': ticket, 'checkin_ok': True})


class ResendConfirmationMail(View):

    def get(self, request, booking_code):
        try:
            booking = Booking.objects.get(code=booking_code)
            send_confirmation_mail(request, booking)
            return HttpResponseRedirect(reverse('booking:confirmation', args=(booking.code,), ) + '#order_confirmation')
        except ObjectDoesNotExist:
            return render(request, 'booking/invalid_ticket_code.html')

booking/templates/booking/confirmation.html
{% load static %}
<!DOCTYPE html>
<html lang="de">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>Romeo und Julia | Theater des WPU Gestalten der Jahrgänge 10 und 7</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700%7CVarela+Round" rel="stylesheet">

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'booking/css/bootstrap.min.css' %}" />

	<!-- Owl Carousel -->
	<link type="text/css" rel="stylesheet" href="{% static 'booking/css/owl.carousel.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'booking/css/owl.theme.default.css' %}" />

	<!-- Magnific Popup -->
	<link type="text/css" rel="stylesheet" href="{% static 'booking/css/magnific-popup.css' %}" />

	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="{% static 'booking/css/font-awesome.min.css' %}">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'booking/css/style.css' %}" />

	<!-- Icon -->
	<link rel="shortcut icon" href="{% static 'booking/img/icon.ico' %}"/>
</head>

<body>
	<!-- Header -->
	<header>


		<!-- Title -->
	<div class="sm-padding bg-grey">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h2 class="">Vielen Dank Für Ihre Bestellung</h2>
					<h3 class="title">Sie erhalten in kürze eine E-Mail mit ihren gebuchten Karten.</h3>
				</div>
			</div>
		</div>
	</div>
	</header>
	<!-- /Header -->

	<div class="section md-padding">
		<div class="container">
			<div class="row">
				<div class="section-header text-center">
					<h3>Sie haben {{ booking.number_of_tickets }} Tickets für {{ booking.performance.title }}
                    am {{ booking.performance.start_date }} gebucht. Die Vorstellung beginnt um {{ booking.performance.start_time }} Uhr.</h3>

					<div class="sm-padding">
						<div class="panel-body"><h2>Links zu der/den gebuchten Theaterkarte/-n:</h2></div>
						<div class="panel-body">
							<ul class="list-unstyled">
                                {% for ticket in tickets %}
                                    <li><h3><a href="{% url 'booking:pdf' ticket.code %}">Ticket {{ ticket.code }}</a></h3></li>
                                {% endfor %}
							</ul>
						</div>
					</div>
					<a href="{% url 'booking:index' %}"><button class="btn btn-lg btn-info">Startseite</button></a>
					<a href="{% url 'booking:index' %}#team"><button class="btn btn-lg btn-success">Mehr Informationen</button></a>
				</div>
		</div>
			<!-- /Row -->
		</div>
		<!-- /Container -->

		<div class="sm-padding bg-grey">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<h2 class="title">Infos über das Theater</h2>
					<p>Romeo und Julia gelten als das berühmteste Liebespaar der Weltliteratur. Der Gestaltenkurs der
						Jahrgangsstufe 10 unter Mitwirkung der Jahrgangsstufe 7 hat sich zum Abschluss ihres Kurses
						vorgenommen, den schon zahlreich in Bühnenaufführungen und Filmen verarbeiteten Stoff in einer neuen
						eigenen Version auf die Bühne zu bringen.
						In Anlehnung an das Original wird die gekürzte ursprüngliche Handlung der Tragödie -sozusagen
						crossover- parallel und abwechselnd in die heutige Zeit übertragen.
						William Shakespeares Tragödie „Romeo und Julia“ wurde 1597 zum ersten Mal in London aufgeführt.
						Die jeweils einzigen Kinder der mächtigen Familien Montague und Capulet in Verona verlieben sich
						ineinander, aber die lange bestehende Feindschaft zwischen den Familien beschwert ihre Liebe und treibt
						Romeo und Julia in den Selbstmord. Erst danach versöhnen sich die Familien.
						Die Motive für das Stück reichen bis in die Dramen der Antike zurück, sind aber bis in die heutige Zeit
						ein immer wiederkehrendes Thema.
						Durch unsere Aufführung erfolgt eine Spiegelung in die heutige Zeit und zeigt eine immerwährende
						Übertragbarkeit von Liebesbeziehungen in alle Gesellschaftsebenen.
						Welche Faktoren könnten hierbei heutzutage eine Rolle spielen?</p>
						<p>Religion?</p>
						<p>Arm oder Reich?</p>
						<p>Gender/Homosexualität?</p>
						<p>Verbotene Liebe?</p>
						<p>Kulturkreis?</p>
				</div>
			</div>
		</div>
	</div>

	</div>
	<!-- /About -->

	<!-- Preloader -->
	<div id="preloader">
		<div class="preloader">
			<span></span>
			<span></span>
			<span></span>
			<span></span>
		</div>
	</div>
	<!-- /Preloader -->

	<!-- jQuery Plugins -->
	<script type="text/javascript" src="{% static 'booking/js/jquery.min.js' %}"></script>
	<!-- jQuery Plugins -->
	<script type="text/javascript" src="{% static 'booking/js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'booking/js/owl.carousel.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'booking/js/jquery.magnific-popup.js' %}"></script>
	<script type="text/javascript" src="{% static 'booking/js/main.js' %}"></script>

</body>

</html>

booking/templates/booking/invalid_ticket_code.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Ungültiger Ticket-Code!
</body>
</html>

booking/templates/booking/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Theaterkarten Bestellbestätigung</title>
</head>
<body>
    <p>
        Sie haben {{ booking.number_of_tickets }} Ticket{% if  booking.number_of_tickets > 1 %}s{% endif %} für die Vorstellung &quot;{{ booking.performance.title }}&quot;
        am {{ booking.performance.start_date }} um {{ booking.performance.start_time }} Uhr bestellt.
    </p>
    <p>
        Laden Sie Ihre Tickets ganz einfach herunter, durch einen einfachen Klick auf den folgenden Link:
    </p>

    <ul style="list-style: None">
    {% for ticket in tickets %}
        <li style="list-style: None"><a href="http://{{ request.get_host }}{% url 'booking:pdf' ticket.code %}">Ticket abrufen</a>
    {% endfor %}
    </ul>

    <p>
        Drucken sie die Tickets aus oder bringen sie ganz einfach ihr Handy mit dem pdf mit und zeigen es am Einlass vor.

        Wir freuen uns auf Ihren Besuch!
    </p>
    <p>
        Mit freundlichen Grüßen,<br/>
        Der Gestaltenkurs der 10. und 7. Jahrgänge
        <br/>
        <i>Bitte antworten Sie nicht auf diese Mail, da diese automatisch erstellt wurde!</i>
    </p>
</body>
</html>

booking/templates/booking/verify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ticket verification</title>
</head>
<body>
    {% if checkin_ok %}
        <div style="background-color:#255625;color:#ffffff;font-weight: bold">
            <h1>Ok</h1>
            <p>Ticket code: {{ ticket.code }}</p>
        </div>
    {% else %}
        <div style="background-color:#ac2925;color:#ffffff;font-weight: bold">
            <p>INVALID</p>
            <p>Invalid ticket code!</p>
        </div>
    {% endif %}
</body>
</html>